In [2]:
import numpy as np

In [4]:
#Creating 1d array 
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [6]:
#Creating 2D 3D array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
#Shape/Dimension of the array
b.shape

(2, 3)

In [10]:
b.ndim

2

In [21]:
#Will start from 1 then take 5 steps and stop at 13
c = np.arange(start=1,stop = 13, step = 5)
c

array([ 1,  6, 11])

In [27]:
#In certain range
d=np.arange(1,11)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
#Reshaping the array into the size of 2x5
e = d.reshape(2,5)
e

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [32]:
#Initializing and reshaping
np.arange(16).reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [37]:
#Reshaping into 5 dimensions
np.arange(32).reshape(2,2,2,2,2)

array([[[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]]],



       [[[[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]],


        [[[24, 25],
          [26, 27]],

         [[28, 29],
          [30, 31]]]]])

In [38]:
#Slicing
d[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
d[5:10]

array([ 6,  7,  8,  9, 10])

In [41]:
d[1:10:2]

array([ 2,  4,  6,  8, 10])

In [50]:
d[-1::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])