**Numpy Notebook**                         
Assignment:                          
1.reshape(-1,1)                    
2.copy()           
3.view()               
4.broadcasting               

In [4]:
import numpy as np

In [10]:
arr=np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
arr.reshape(-1,1) #By itself reshaps the array in dimensions such that there is 1 element
#If it was (-1,2) then array would be like [[0,1][2,3]...]

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [18]:
arr2=arr.copy()
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [25]:
arr3=arr2.view()
arr3[0]=10  #Modifying the element in arr3 will also affect arr2 as both points towards same location
arr2

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [32]:
#Broadcasting
a=np.arange(10)
b=np.arange(10,20)
print(a)
print(b)
print(a+b)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18 20 22 24 26 28]
